// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://npovdaakbbdcarjvvknd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wb3ZkYWFrYmJkY2FyanZ2a25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxODU5NzEsImV4cCI6MjA0Nzc2MTk3MX0.ReEjxl3fKmrWAaEKXry-l-pzvFFsyRDnmYeBP0Dzx9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);